#!/bin/bash
# Skill 发现器
# 从 ClawHub 和 GitHub 自动发现有用的 OpenClaw Skills

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 配置
KEYWORD="${1:-openclaw}"
OUTPUT_DIR="${OUTPUT_DIR:-/tmp/skills}"
mkdir -p "$OUTPUT_DIR"

echo -e "${BLUE}🦞 OpenClaw Skill 发现器${NC}"
echo -e "${YELLOW}搜索关键词: $KEYWORD${NC}\n"

# 从 GitHub 搜索 Skills
search_github_skills() {
    echo -e "${GREEN}=== GitHub Skills ===${NC}"
    gh search repos "$KEYWORD openclaw skill" --sort stars --limit 10 \
        --json fullName,description,stargazersCount,url,updatedAt 2>/dev/null | \
        jq -r '.[] | "⭐ \(.stargazersCount) | \(.fullName)\n   \(.description)\n   更新: \(.updatedAt)\n   链接: \(.url)"' 
}

# 搜索 awesome-openclaw-skills
search_awesome_skills() {
    echo -e "\n${GREEN}=== Awesome OpenClaw Skills ===${NC}"
    
    # 克隆或更新 awesome-openclaw-skills
    AWESOME_DIR="$OUTPUT_DIR/awesome-openclaw-skills"
    if [ -d "$AWESOME_DIR" ]; then
        cd "$AWESOME_DIR" && git pull -q
    else
        git clone -q https://github.com/VoltAgent/awesome-openclaw-skills.git "$AWESOME_DIR"
    fi
    
    # 搜索 README 中的关键词
    if [ -f "$AWESOME_DIR/README.md" ]; then
        grep -i -A 2 "$KEYWORD" "$AWESOME_DIR/README.md" | head -20 || echo "未找到匹配项"
    fi
}

# 生成报告
generate_report() {
    REPORT_FILE="$OUTPUT_DIR/skills-report-$(date +%Y-%m-%d).md"
    
    echo "# OpenClaw Skills 发现报告" > "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "**搜索关键词**: $KEYWORD" >> "$REPORT_FILE"
    echo "**生成时间**: $(date '+%Y-%m-%d %H:%M:%S')" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    
    echo "## GitHub 搜索结果" >> "$REPORT_FILE"
    gh search repos "$KEYWORD openclaw skill" --sort stars --limit 10 \
        --json fullName,description,stargazersCount,url 2>/dev/null | \
        jq -r '.[] | "- [**\(.fullName)**](\(.url)) ⭐\(.stargazersCount)\n  \(.description)"' >> "$REPORT_FILE"
    
    echo "" >> "$REPORT_FILE"
    echo "---" >> "$REPORT_FILE"
    echo "🦞 Generated by Miaoquai OpenClaw Tools" >> "$REPORT_FILE"
    
    echo -e "\n${GREEN}✅ 报告已生成: $REPORT_FILE${NC}"
}

# 主函数
main() {
    if ! command -v gh &> /dev/null; then
        echo -e "${RED}错误: 需要 gh (GitHub CLI)${NC}"
        exit 1
    fi
    
    search_github_skills
    
    echo ""
    generate_report
}

main "$@"
