#!/bin/bash
# OpenClaw Skills Dependency Checker
# 自动检查 OpenClaw Skills 的依赖更新并提交 PR
# Author: 妙趣AI (miaoquai.com)
# Version: 1.0.0
# Date: 2026-04-13

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# 配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE_DIR="${SCRIPT_DIR}/.skill-cache"
DEPENDENCY_REPORTS_DIR="${SCRIPT_DIR}/dependency-reports"
GITHUB_USERNAME="${GITHUB_USERNAME:-jingchang0623-crypto}"
GIT_USER_NAME="${GIT_USER_NAME:-MiaoquAI Bot}"
GIT_USER_EMAIL="${GIT_USER_EMAIL:-bot@miaoquai.com}"

# 初始化
init() {
    mkdir -p "${CACHE_DIR}"
    mkdir -p "${DEPENDENCY_REPORTS_DIR}"
    
    # 配置 Git
    git config --global user.name "${GIT_USER_NAME}" 2>/dev/null || true
    git config --global user.email "${GIT_USER_EMAIL}" 2>/dev/null || true
}

# 日志函数
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

log_error() {
    echo -e "${RED}[✗]${NC} $1"
}

# 显示帮助
show_help() {
    cat << 'EOF'
🦞 OpenClaw Skills Dependency Checker
   自动检查并更新 OpenClaw Skills 依赖

Usage:
  ./skill-dependency-checker.sh [command] [options]

Commands:
  check [path]          检查指定目录或文件的依赖 (默认: 当前目录)
  report                生成依赖报告
  trending              检查 Trending 项目的依赖
  help                  显示帮助

Examples:
  # 检查当前目录的依赖
  ./skill-dependency-checker.sh check

  # 检查今日 Trending 项目
  ./skill-dependency-checker.sh trending

Generated by: 妙趣AI (https://miaoquai.com)
EOF
}

# 获取 NPM 包最新版本
get_npm_latest_version() {
    local package="$1"
    local cache_file="${CACHE_DIR}/npm_${package//\//_}.json"
    
    # 检查缓存（1小时有效期）
    if [[ -f "$cache_file" ]]; then
        local cache_age=$(($(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || stat -f %m "$cache_file")))
        if [[ $cache_age -lt 3600 ]]; then
            jq -r '.["dist-tags"].latest' "$cache_file" 2>/dev/null && return 0
        fi
    fi
    
    # 获取最新版本
    local response
    response=$(curl -s "https://registry.npmjs.org/${package}" 2>/dev/null)
    
    if [[ $? -eq 0 ]] && [[ -n "$response" ]]; then
        echo "$response" > "$cache_file"
        echo "$response" | jq -r '.["dist-tags"].latest' 2>/dev/null
    else
        echo ""
    fi
}

# 获取 PyPI 包最新版本
get_pypi_latest_version() {
    local package="$1"
    local cache_file="${CACHE_DIR}/pypi_${package}.json"
    
    if [[ -f "$cache_file" ]]; then
        local cache_age=$(($(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || stat -f %m "$cache_file")))
        if [[ $cache_age -lt 3600 ]]; then
            jq -r '.info.version' "$cache_file" 2>/dev/null && return 0
        fi
    fi
    
    local response
    response=$(curl -s "https://pypi.org/pypi/${package}/json" 2>/dev/null)
    
    if [[ $? -eq 0 ]] && [[ -n "$response" ]]; then
        echo "$response" > "$cache_file"
        echo "$response" | jq -r '.info.version' 2>/dev/null
    else
        echo ""
    fi
}

# 获取 GitHub Release 最新版本
get_github_latest_release() {
    local repo="$1"
    local cache_file="${CACHE_DIR}/gh_${repo//\//_}.json"
    
    if [[ -f "$cache_file" ]]; then
        local cache_age=$(($(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || stat -f %m "$cache_file")))
        if [[ $cache_age -lt 3600 ]]; then
            jq -r '.tag_name' "$cache_file" 2>/dev/null | sed 's/^v//' && return 0
        fi
    fi
    
    local response
    response=$(gh api "repos/${repo}/releases/latest" 2>/dev/null)
    
    if [[ $? -eq 0 ]] && [[ -n "$response" ]]; then
        echo "$response" > "$cache_file"
        echo "$response" | jq -r '.tag_name' 2>/dev/null | sed 's/^v//'
    else
        echo ""
    fi
}

# 比较版本号
version_compare() {
    local v1="$1"
    local v2="$2"
    
    # 移除前缀 v 或 V
    v1="${v1#v}"
    v1="${v1#V}"
    v2="${v2#v}"
    v2="${v2#V}"
    
    if [[ "$v1" == "$v2" ]]; then
        echo 0
        return
    fi
    
    # 使用 sort -V 进行版本比较
    if printf '%s\n%s\n' "$v1" "$v2" | sort -V -C; then
        echo -1  # v1 < v2
    else
        echo 1   # v1 > v2
    fi
}

# 检查 package.json 依赖
check_npm_dependencies() {
    local file="$1"
    local updates=()
    
    log_info "检查 NPM 依赖: $file"
    
    if [[ ! -f "$file" ]]; then
        log_error "文件不存在: $file"
        return 1
    fi
    
    # 解析 dependencies 和 devDependencies
    local deps_json
    deps_json=$(cat "$file")
    
    # 检查每个依赖
    local packages
    packages=$(echo "$deps_json" | jq -r '(.dependencies // {}) + (.devDependencies // {}) | keys[]' 2>/dev/null)
    
    while IFS= read -r package; do
        [[ -z "$package" ]] && continue
        
        local current_version
        current_version=$(echo "$deps_json" | jq -r --arg pkg "$package" '.dependencies[$pkg] // .devDependencies[$pkg]' 2>/dev/null | tr -d '^~>=<')
        
        local latest_version
        latest_version=$(get_npm_latest_version "$package")
        
        if [[ -n "$latest_version" ]] && [[ -n "$current_version" ]]; then
            local cmp
            cmp=$(version_compare "$current_version" "$latest_version")
            
            if [[ "$cmp" == "-1" ]]; then
                log_warning "📦 $package: $current_version → $latest_version"
                updates+=("{\"package\":\"$package\",\"current\":\"$current_version\",\"latest\":\"$latest_version\",\"type\":\"npm\"}")
            elif [[ "$cmp" == "0" ]]; then
                log_success "✓ $package: $current_version (最新)"
            fi
        fi
    done <<< "$packages"
    
    printf '%s\n' "${updates[@]}"
}

# 检查 requirements.txt 依赖
check_pip_dependencies() {
    local file="$1"
    local updates=()
    
    log_info "检查 Python 依赖: $file"
    
    if [[ ! -f "$file" ]]; then
        log_error "文件不存在: $file"
        return 1
    fi
    
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        [[ "$line" == \#* ]] && continue
        
        # 解析包名和版本
        local package=""
        local version=""
        
        # 使用简单字符串处理替代正则
        if [[ "$line" == *"=="* ]]; then
            package="${line%%==*}"
            version="${line#*==}"
        elif [[ "$line" == *">="* ]]; then
            package="${line%%>=*}"
            version="${line#*>=}"
        fi
        
        # 清理空白字符
        package=$(echo "$package" | xargs)
        version=$(echo "$version" | xargs)
        
        [[ -z "$package" ]] && continue
        [[ -z "$version" ]] && continue
        
        local latest_version
        latest_version=$(get_pypi_latest_version "$package")
        
        if [[ -n "$latest_version" ]]; then
            local cmp
            cmp=$(version_compare "$version" "$latest_version")
            
            if [[ "$cmp" == "-1" ]]; then
                log_warning "🐍 $package: $version → $latest_version"
                updates+=("{\"package\":\"$package\",\"current\":\"$version\",\"latest\":\"$latest_version\",\"type\":\"pip\"}")
            elif [[ "$cmp" == "0" ]]; then
                log_success "✓ $package: $version (最新)"
            fi
        fi
    done < "$file"
    
    printf '%s\n' "${updates[@]}"
}

# 检查 SKILL.md 中的工具依赖
check_skill_dependencies() {
    local file="$1"
    local updates=()
    
    log_info "检查 SKILL 工具依赖: $file"
    
    if [[ ! -f "$file" ]]; then
        log_error "文件不存在: $file"
        return 1
    fi
    
    # 提取工具清单中的工具
    local content
    content=$(cat "$file")
    
    # 查找 GitHub 工具链接
    local github_tools
    github_tools=$(echo "$content" | grep -oE 'github\.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+' | sort -u)
    
    while IFS= read -r tool; do
        [[ -z "$tool" ]] && continue
        
        local repo="${tool#github.com/}"
        log_info "检查工具: $repo"
        
        # 尝试获取最新 release
        local latest_version
        latest_version=$(get_github_latest_release "$repo")
        
        if [[ -n "$latest_version" ]]; then
            log_info "  最新版本: v$latest_version"
            updates+=("{\"package\":\"$repo\",\"current\":\"unknown\",\"latest\":\"$latest_version\",\"type\":\"github\"}")
        fi
    done <<< "$github_tools"
    
    printf '%s\n' "${updates[@]}"
}

# 扫描目录查找依赖文件
scan_directory() {
    local dir="$1"
    local deps_files=()
    
    log_info "扫描目录: $dir"
    
    # 查找各种依赖文件
    while IFS= read -r -d '' file; do
        deps_files+=("$file")
    done < <(find "$dir" -maxdepth 2 -type f \( \
        -name "package.json" -o \
        -name "requirements.txt" -o \
        -name "SKILL.md" \
    \) -print0 2>/dev/null)
    
    printf '%s\n' "${deps_files[@]}"
}

# 生成依赖检查报告
generate_report() {
    local target="${1:-.}"
    local timestamp
    timestamp=$(date +%Y-%m-%d_%H%M%S)
    local report_file="${DEPENDENCY_REPORTS_DIR}/dependency-report-${timestamp}.md"
    
    log_info "生成依赖检查报告..."
    
    # 收集所有依赖信息
    local all_updates=()
    local deps_files
    
    if [[ -f "$target" ]]; then
        deps_files=("$target")
    else
        mapfile -t deps_files < <(scan_directory "$target")
    fi
    
    # 开始生成报告
    cat > "$report_file" << EOF
# 📦 OpenClaw Skills 依赖检查报告

**生成时间**: $(date '+%Y-%m-%d %H:%M:%S')  
**检查目标**: $target  
**生成者**: 妙趣AI (https://miaoquai.com)

---

## 📊 汇总概览

| 项目 | 数量 |
|------|------|
| 检查的依赖文件 | ${#deps_files[@]} |

## 🔍 详细检查结果

EOF

    for file in "${deps_files[@]}"; do
        local file_type
        if [[ "$file" == *"package.json"* ]]; then
            file_type="npm"
        elif [[ "$file" == *"requirements.txt"* ]]; then
            file_type="pip"
        elif [[ "$file" == *"SKILL.md"* ]]; then
            file_type="openclaw-skill"
        else
            file_type="unknown"
        fi
        
        echo "" >> "$report_file"
        echo "### $(basename "$file")" >> "$report_file"
        echo "" >> "$report_file"
        echo "- **路径**: \`$file\`" >> "$report_file"
        echo "- **类型**: $file_type" >> "$report_file"
        echo "" >> "$report_file"
        
        local updates
        case "$file_type" in
            npm)
                mapfile -t updates < <(check_npm_dependencies "$file")
                ;;
            pip)
                mapfile -t updates < <(check_pip_dependencies "$file")
                ;;
            openclaw-skill)
                mapfile -t updates < <(check_skill_dependencies "$file")
                ;;
            *)
                echo "> ⚠️ 不支持的文件类型" >> "$report_file"
                continue
                ;;
        esac
        
        if [[ ${#updates[@]} -gt 0 ]] && [[ -n "${updates[0]}" ]]; then
            echo "#### 可更新的依赖" >> "$report_file"
            echo "" >> "$report_file"
            echo "| 包名 | 当前版本 | 最新版本 | 操作 |" >> "$report_file"
            echo "|------|----------|----------|------|" >> "$report_file"
            
            for update in "${updates[@]}"; do
                if [[ -n "$update" ]]; then
                    local pkg cur latest type
                    pkg=$(echo "$update" | jq -r '.package')
                    cur=$(echo "$update" | jq -r '.current')
                    latest=$(echo "$update" | jq -r '.latest')
                    type=$(echo "$update" | jq -r '.type')
                    echo "| $pkg | $cur | $latest | [查看](https://npmjs.com/package/$pkg) |" >> "$report_file"
                fi
            done
            echo "" >> "$report_file"
        else
            echo "> ✅ 所有依赖都是最新版本" >> "$report_file"
            echo "" >> "$report_file"
        fi
    done
    
    # 添加页脚
    cat >> "$report_file" << EOF

---

## 🚀 快速操作

\`\`\`bash
# 检查今日 Trending 项目
./skill-dependency-checker.sh trending

# 更多功能请查看帮助
./skill-dependency-checker.sh help
\`\`\`

---

*本报告由 [妙趣AI](https://miaoquai.com) 自动生成* 🤖
EOF

    log_success "报告已生成: $report_file"
    echo "$report_file"
}

# 检查今日 Trending 项目
check_trending() {
    log_info "检查今日 GitHub Trending OpenClaw 项目..."
    
    # 计算昨天的日期
    local yesterday
    yesterday=$(date -d '1 day ago' +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d)
    
    # 获取今日新创建的 OpenClaw 项目
    local repos
    repos=$(gh api "search/repositories?q=openclaw+created:>${yesterday}&sort=stars&order=desc" \
        --jq '.items[] | "\(.full_name)|\(.description)|\(.stargazers_count)|\(.html_url)"' 2>/dev/null | head -10)
    
    if [[ -z "$repos" ]]; then
        log_warning "没有找到今日新的 OpenClaw 项目"
        return 0
    fi
    
    log_info "发现 $(echo "$repos" | wc -l) 个新项目"
    
    local timestamp
    timestamp=$(date +%Y-%m-%d)
    local report_file="${DEPENDENCY_REPORTS_DIR}/trending-check-${timestamp}.md"
    
    cat > "$report_file" << EOF
# 🔥 OpenClaw Trending 项目依赖检查

**日期**: $(date '+%Y-%m-%d')  
**生成者**: 妙趣AI (https://miaoquai.com)

---

## 📈 今日 Trending 项目

| 项目 | 描述 | Stars | 依赖状态 |
|------|------|-------|----------|
EOF

    while IFS='|' read -r repo desc stars url; do
        [[ -z "$repo" ]] && continue
        
        log_info "检查: $repo"
        
        # 检查是否有 package.json 或 requirements.txt
        local has_deps="❌ 无"
        gh api "repos/${repo}/contents/package.json" 2>/dev/null && has_deps="✅ NPM"
        gh api "repos/${repo}/contents/requirements.txt" 2>/dev/null && has_deps="✅ Python"
        
        # 截断描述
        local short_desc="${desc:0:40}"
        if [[ ${#desc} -gt 40 ]]; then
            short_desc="${short_desc}..."
        fi
        
        echo "| [$repo]($url) | $short_desc | ⭐ $stars | $has_deps |" >> "$report_file"
    done <<< "$repos"
    
    cat >> "$report_file" << EOF

---

## 💡 建议

对于标记为 ✅ 的项目，可以：
1. Fork 项目
2. 运行依赖检查
3. 提交 PR 帮助更新依赖

\`\`\`bash
# 批量检查 Trending 项目
./skill-dependency-checker.sh trending
\`\`\`

---

## 🔗 相关链接

- [妙趣AI](https://miaoquai.com) - AI工具导航 + 资讯平台
- [OpenClaw 官方](https://openclaw.ai)

---

*由 [妙趣AI](https://miaoquai.com) 自动生成* 🤖
EOF

    log_success "Trending 检查报告: $report_file"
    echo "$report_file"
}

# 主函数
main() {
    init
    
    local command="${1:-help}"
    shift || true
    
    case "$command" in
        check)
            local target="${1:-.}"
            generate_report "$target"
            ;;
        report)
            local target="${1:-.}"
            generate_report "$target"
            ;;
        trending)
            check_trending
            ;;
        help|--help|-h)
            show_help
            ;;
        *)
            log_error "未知命令: $command"
            show_help
            exit 1
            ;;
    esac
}

# 如果直接运行脚本
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi